### ISSUE TITLE
incompatible query with sql_mode ONLY_FULL_GROU_BY

### ISSUE THREAD

**Issue by MayurAgarkar** [snapcrescent/snapcrescent#20]
Hi,

I have mysql 5.7.5+ installed which has the default SQL mode ONLY_FULL_GROUP_BY
This causes the login of app to fail with error 

`Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'snap_crescent.m1_0.creation_date_time' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by`

I had to update mysql db to disable ONLY_FULL_GROUP_BY and then the login worked. 
This needs a query fix or instruction to use mysql lower than 5.7.5

Thanks !

**Comment by navalgandhi1989** [comment]
@MayurAgarkar  updated README.md
